### ISSUE TITLE
When adding a new Document with some Links

### ISSUE THREAD

**Issue by lorericci** [umberto-fontanazza/kiruna-explorer#124]
When I add a new Document with some Links (more than 1), the Document view in the sidebar is correct but non the Link part, that is always 1. When I press the visualLinks button everything become correct, with the correct number of links added in the DocumentForm .

**Comment by lorericci** [comment]
Update: Sometimes works with 2 and sometimes don't

**Comment by lorericci** [comment]
Fix also the flickering

**Comment by emanuelefrisi** [comment]
Fixed
