### ISSUE TITLE
Button of map and Documents

### ISSUE THREAD

**Issue by s321387** [umberto-fontanazza/kiruna-explorer#126]
When selecting one of them or being in some of the pages would be useful to keep the button with another color, so the user know that is in that specific page.

**Comment by emanuelefrisi** [comment]
@s321387 Can you better describe this issue?

**Comment by s321387** [comment]
Yes, I mean to leave underlined or selected the page where the user is, that is to say, if I am in “Map” to signal in the map button that I am already there, the same for documents and Uploads.

**Comment by emanuelefrisi** [comment]
Fixed
