### ISSUE TITLE
Mixed filters

### ISSUE THREAD

**Issue by s321387** [umberto-fontanazza/kiruna-explorer#135]
When the filters are mixed in the Urban Planner profile, in the documents section, and more than two filters are selected, the application does not work.

**Comment by s321387** [comment]
![Screenshot 2024-11-29 085857](https://github.com/user-attachments/assets/0d3e9458-5b47-4440-a9ae-6afc449c39b7)
![Screenshot 2024-11-29 090042](https://github.com/user-attachments/assets/62c49009-7f75-4229-aa09-758c886d0f9b)

**Comment by s321387** [comment]
It also happens if the two date filters are used at the same time.

**Comment by s321387** [comment]
Also in the E2E tests happens the same thing
![image](https://github.com/user-attachments/assets/6c02a420-f44b-4288-9230-fc1ef25b881d)

**Comment by umberto-fontanazza** [comment]
This was solved with PR #137
