### ISSUE TITLE
Demo #3 Feedbacks

### ISSUE THREAD

**Issue by lorericci** [umberto-fontanazza/kiruna-explorer#162]
1. ~Add insertion of custom stakeholders~
2. ~IssuanceTime is a required field with either YYYY / YYYY-MM / YYYY-MM-DD UTC~
3. ~Document position may change from area to coordinates and vice versa~
4. The carousel visualization of documents can be visualized when the filters are applied.

**Comment by emanuelefrisi** [comment]
The forth one won't be fixed
