### ISSUE TITLE
Swap from polyon to position during document insertion

### ISSUE THREAD

**Issue by umberto-fontanazza** [umberto-fontanazza/kiruna-explorer#164]
To reproduce after loggin in:
1. visit the map page
2. insert new document
3. click on the map (now you have inserted the first point of the polygon)
4. switch to single position rather than area
5. The for states 'polygon area was registered'

This is clearly a bug because:

- polygons should at least have three points 
- the user wanted to insert a single position rather than an area

**Comment by lorericci** [comment]
Fixed
