### ISSUE TITLE
Remove dotenv for consistent management over the CI pipeline

### ISSUE THREAD

**Issue by umberto-fontanazza** [umberto-fontanazza/kiruna-explorer#21]
I am considering dropping the dotenv package and just use node env variables. I found an interesting [article](https://medium.com/@tony.infisical/stop-using-dotenv-in-node-js-v20-6-0-8febf98f6314) about it.

This would mean we should deploy the backend on Node v20.6.0+ but since the backend is usually dockerized this should not be a problem.

Right now the CI pipeline has the variables set by the workflow (it's not using dotenv) while the npm scripts 'dev' and 'test' use dotenv.

**Comment by emanuelefrisi** [comment]
I've read the article. Consider that we are using nodemon. It doesn't allow the env file flag like the node command. However nodemon can be configured by creating a config file named `nodemon.json`. Source: `nodhttps://github.com/remy/nodemon/issues/2153

**Comment by emanuelefrisi** [comment]
I was trying to solve this issue. It works for development mode by using in package.json:
`nodemon --exec node --env-file=.env -r ts-node/register ./src/index.ts`.
By the way it can't be the same on the test part. Jest doesn't support native environment variables. We'll mantain the `dotenv` library.
