### ISSUE TITLE
Id title in the Sidebar

### ISSUE THREAD

**Issue by lorericci** [umberto-fontanazza/kiruna-explorer#38]
The id in the title is saved in the db, so i cannot fix. 
Example: Compilation of responses “So what the people of Kiruna think?” (15) -> this (15) has to be deleted from all documents in the db, according to the product owner during the demo

**Comment by emanuelefrisi** [comment]
That is not the id of the document. That is part of the title. When adding a new document I simply copied the title of the cards that they have proposed us. Anyway, I'm changing it from the db
