### ISSUE TITLE
Duplicate Number() parsing Zod 

### ISSUE THREAD

**Issue by umberto-fontanazza** [umberto-fontanazza/kiruna-explorer#7]
Validation of id request.parameter in some /documents routes is performed with zod middleware requiring a schema.
In PR #6 the middleware to validate id uses .coerce (which parses the number from a string). However this parsing is forgotten when the validation check passes and the route handler performs again the parsing.

An improvement would be to edit the request being passed to the next middleware and access it in the route handler with the result of parsing from the validation step.

**Comment by emanuelefrisi** [comment]
This can be done by adding some lines of code, so the redundancy in this case is accepted
