### ISSUE TITLE
Inexplicable addition to coordinates

### ISSUE THREAD

**Issue by umberto-fontanazza** [umberto-fontanazza/kiruna-explorer#75]
While refactoring the Map component #74 I came across this piece of code
```
          setCenter({
            lat: doc.coordinates?.latitude!,
            lng: doc.coordinates?.longitude! + 0.0019,
          });
```
I never understood why a constant is added to longitude. I left a TODO: in the PR but this either need a comment or to be removed if that's the case.

**Comment by michepaolo** [comment]
Without that addition the selected document would be in the center of the whole screen, but we want that, when we select a document and the sidebar appears, the selected document appears in the center of the remaining part of the screen -> we have to shift it a bit to the left.

**Comment by umberto-fontanazza** [comment]
In this case I suggest shrinking the HTML element containing the map, leaving space for the sidebar OR showing only the document card without the sidebar. If it's ok for everyone I can proceed with this change

**Comment by michepaolo** [comment]
Trying it I noticed that it doesn't work anymore. For me you can do whatever you want
