### ISSUE TITLE
Demo #1 feedback from group 9

### ISSUE THREAD

**Issue by minasamadi** [umberto-fontanazza/kiruna-explorer#84]
Hi everyone,

I had a couple of suggestions regarding the demo:
Missing Field: The Date field was forgotten on the form for creating the document. 
Layout Improvement: The fields on the form were not too many, so I suggested arranging them in two columns to reduce the need for scrolling and improve the overall user experience.

Thanks,
Mina Samadi

**Comment by umberto-fontanazza** [comment]
Thank you, this was indeed implemented accoding to the feedback
