### ISSUE TITLE
Demo #2 feedback

### ISSUE THREAD

**Issue by umberto-fontanazza** [umberto-fontanazza/kiruna-explorer#87]
Stakeholder feedback from meeting of 21-11-2024:

1. ~Documents should be editable from the document list (provide a button opening the form)~
2. ~Rename ratio > architectural scale in the document form~
3. The issuance year is mandatory
4. ~Propose a solution to visualize documents with the same exact position (same coordinates)~ --> Sprint 4 - KX-20
5. ~Provide a way to assign to a document the position of a previous positioned document~ --> Sprint 4 - KX-19
6. ~Implement drag and drop to edit coordinates~
7. ~When editing coordinates display the previous position~
8. In the document form provide a feedback for invalid input
9. ~Remove "select option" option from document scale type selector~
10. Don't display coordinates in the document form --> Enhance coordinate validation and control
11. ~Center map on selected document + transition~

**Comment by lorericci** [comment]
1. First point done

**Comment by umberto-fontanazza** [comment]
Remaining issues are in the demo 3 feedback
