### ISSUE TITLE
DELETE /sessions/current when not logged in

### ISSUE THREAD

**Issue by umberto-fontanazza** [umberto-fontanazza/kiruna-explorer#9]
Currently the API docs don't tackle the problem of trying to log out an user who is not logged in.
In my opinion returning a status code BAD_REQUEST would be more appropriate. This was introduced with PR #8

**Comment by emanuelefrisi** [comment]
This was solved with the addition of the authentication middleware `isLoggedIn` to route `DELETE /sessions/current`
