### ISSUE TITLE
Issuance Date

### ISSUE THREAD

**Issue by s321387** [umberto-fontanazza/kiruna-explorer#91]
There is a problem with the dates because when they are inserted manually it does not work and the system is damaged.

**Comment by umberto-fontanazza** [comment]
Please further describe the issue in such a way that it can be reproduced. 
What does it mean to insert a date manually? 
What is the error shown?
...

**Comment by s321387** [comment]
It is already solved, I don't know specifically what it was solved with, but it doesn't happen anymore.
