### ISSUE TITLE
Frontend Guidelines 

### ISSUE THREAD

**Issue by lorericci** [umberto-fontanazza/kiruna-explorer#96]
- `One and only one component per file`
- `Filename of the component matches the component name`
- `The default export of the component file is a component`
- `Props interface is defined before the component in the component file`
- `No styles in the component`
- `Every component has it's own .scss file imported`
- `Component specific rulesets must not exceed the component html scope`

**Comment by emanuelefrisi** [comment]
These were only written but not properly followed
